### ISSUE TITLE
Upgrade to qt5.5 cause fcitx-qt to fail start in kwrite

### ISSUE THREAD

**Issue by zwpwjwtz** [fcitx/fcitx-qt5#10]
Upgrade to qt5.5 cause fcitx-qt to fail start in Kwrite, Konsole and other qt5-based program.
No debug information related to fcitx found in stdout.

Using Fedora 22 KDE, fcitx-1.0.2.

**Comment by yuyichao** [comment]
fcitx-qt needs to be recompiled when upgrading Qt

**Comment by zwpwjwtz** [comment]
Compiled under instruction from http://my.oschina.net/lieefu/blog/505363. It works.
I wonder how distributions like Fedora will solve problems of this kind (incompatibility due to upgrade of base library).

**Comment by wengxt** [comment]
Well, you should report it to fedora to ask them to recompile it (and they will bump pkg rel).

**Comment by wengxt** [comment]
I sent a email to the maintainer. He said he will update it asap.

**Comment by wengxt** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2015-16517
https://bodhi.fedoraproject.org/updates/FEDORA-2015-16516
https://bodhi.fedoraproject.org/updates/FEDORA-2015-16515

Try and give positive feedback in corresponding page above will make the updates enter [updates] faster.
