### ISSUE TITLE
libxkbcommon version conflict?

### ISSUE THREAD

**Issue by Jichao** [fcitx/fcitx-qt5#11]
The project required libxkbcommon >= 0.5.0 but qt 5.5.0 use 0.4.1. When I close a qt application, the application would crash.

![2015-10-13 15 16 07](https://cloud.githubusercontent.com/assets/426019/10451254/a305da16-71d1-11e5-956b-3f954700de98.png)

Env:
OS: Ubuntu 14.04.3 LTS

Steps to reproduce the problem:
1) download qt-everywhere-opensource-src-5.5.0.tar.gz and build it.
2) follow the instructions http://my.oschina.net/lieefu/blog/505363 to install the fcitx qt immodule. Which would replace the default libxkbcommon0.
3) create a simple qt application, and then close it. it would crash at the above position.
4) remove the newer libxkbcommon0.5.0 and reinstall the system package, delete the libfcitxplatforminput.so, the problem gone.

I checked the qt5.6 source code, it still use libxkbcommon0.4.1, qt5.5.0 static link the libxkbcommon to libQt5XcbQpa.so, but the xcb plugin requires the shared libxkbcommon.so.

 Do I need to upgrade the qtbase/src/3rdparty/xkbcommon code, or maybe rebuild the qt5.5.0?

**Comment by wengxt** [comment]
You can just make qt use your system libxkbcommon. Every distro packages their qt without any bundled package.

**Comment by Jichao** [comment]
configure qt5.5.0 with
  xkbcommon-x11........... yes (system library)
  xkbcommon-evdev......... yes

Qt5.5.0 would need xkbcommon-x11 library, however fcitx-qt5 need xkbocmmon. So we need to build xkbcommon twice, once with --disable-x11 once without it.

In conclusion, it is not version conflict.

**Comment by wengxt** [comment]
I'm not aware that libxkbcommon break abi recently. I have no problem with qt 5.5.0 and libxkbcommon 0.5.0 on my system. In conclusion, I don't think there's any problem on fcitx side, and xkbcommon has no internal state that fcitx might modified and cause some other library using it at the same time to crash.

You may consider following advice:
1 .If your system has no eligible libxkbcommon, install it as system library first.
2. build qt 5.5.0 with it
3. build fcitx-qt with it and qt

**Comment by Jichao** [comment]
It is not the problem of fcitx-qt5. It is qt5.5.0 which need x11 version of xkbcommon if built with system xkbcommon.
In qxcbkeyboard.cpp, 

#ifndef QT_NO_XKB
    if (connection()->hasXKB()) {
        xkb_keymap = xkb_x11_keymap_new_from_device(xkb_context, xcb_connection(), core_device_id, (xkb_keymap_compile_flags)0);
        if (xkb_keymap) {
            // Create a new keyboard state object for a keymap
            new_state = xkb_x11_state_new_from_device(xkb_keymap, xcb_connection(), core_device_id);
        }
    }
#endif

xkb_keymap will not be initialized correctly, if there is no libxkbcommon-x11 library.
I do not know much about the problem, but after building libxkbcommon-x11, the problem is  solved .
