### ISSUE TITLE
在QT5.5.1环境中编译fcitx-qt5的时候，ECM和XKBCommon 一定要用终端提示的版本才行么？

### ISSUE THREAD

**Issue by linux0ne** [fcitx/fcitx-qt5#16]
ECM部分的提示如下:
CMake Error at CMakeLists.txt:8 (find_package):

  Could not find a package configuration file provided by "ECM" (requested

  version 1.4.0) with any of the following names:

    ECMConfig.cmake

    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"

  to a directory containing one of the above files.  If "ECM" provides a

  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!

XKBCommon部分的提示如下：

-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 

-- Could NOT find XKBCommon_XKBCommon (missing:  XKBCommon_XKBCommon_LIBRARY XKBCommon_XKBCommon_INCLUDE_DIR) 

CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):

  Could NOT find XKBCommon (missing: XKBCommon_LIBRARIES XKBCommon) (Required

  is at least version "0.5.0")

---------------------------------------------------------------------------------------------------

一定要用1.4版本和0.5版本么？？   现在最新的版本可以用么？？

**Comment by linux0ne** [comment]
我都用最新版本的，最终也提示编译通过了。但是在qt5.5.1编译出来的程序中输入字符时出现下面的错误：

     因为XKBCommon涉及键盘的问题，而在用键盘输入英文的时候，发现错误：
1、输入小写字母时竟然显示大写字母，而键盘的大小写锁定键没有开启。

2、输入英文的"."时，竟然出了上档键的效果，即">"。

有什么办法么？？   貌似shift键被人“按住”了一样！好恐怖。

**Comment by wengxt** [comment]
no idea. 最有可能的原因是你系统 xkb 配置和 xkbcommon 之间有兼容问题
