### ISSUE TITLE
fcitx-frontend-qt5 in KDE neon can not be install in a dependency problem.

### ISSUE THREAD

**Issue by fu-sen** [fcitx/fcitx-qt5#17]
I tried to use the fcitx in KDE neon.

https://neon.kde.org/

As a result, it does not work Fcitx in qt5 application.

I investigated the fcitx package apt. As a result, fcitx-frotnend-qt5 has not been installed.
As a result of trying to install a fcitx-frotnend-qt5 with apt it has become state:

```
balloon@KDE-neon:~$ LANG=C sudo apt install fcitx-frontend-qt5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) fcitx-frontend-qt5 [ amd64 ] < none -> 1.0.5-1 > ( libs )
Broken fcitx-frontend-qt5:amd64 Depends on qtbase-abi-5-5-1 [ amd64 ] < none > ( none )
  Considering libqt5core5a:amd64 2528 as a solution to fcitx-frontend-qt5:amd64 10005
  Considering libqt5core5a:amd64 2528 as a solution to fcitx-frontend-qt5:amd64 10005
Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 fcitx-frontend-qt5 : Depends: qtbase-abi-5-5-1
E: Unable to correct problems, you have held broken packages.
balloon@KDE-neon:~$
```
This problem is Plasma and qt of KDE neon is in the new things from the Ubuntu package (Kubuntu).
but at present there is a possibility that the same problem in the release after the Ubuntu (Kubuntu).
I went the report, to request an improvement in one of the now.

**Comment by wengxt** [comment]
Well, neon has newer qt. but fcitx-qt5 need to be recompiled if qt updates. You need to ask neon to provides their own fcitx-qt5 against their qt.

**Comment by Zazck** [comment]
https://packages.debian.org/sid/libs/fcitx-frontend-qt5 download and install this, ALL OK but SDL won't support fcitx in valve games, for now just use ibus instead(no steam client input support)

**Comment by wengxt** [comment]
@Zazck  SDL is SDL.. it has nothing to do with Qt.

As for SDL, FYI: https://bugzilla.libsdl.org/show_bug.cgi?id=2824

**Comment by wengxt** [comment]
I put a bug report on bko, not sure if they'll accept it.

https://bugs.kde.org/show_bug.cgi?id=367519

**Comment by idmresettrial** [comment]
@fu-sen It's been fixed now: https://bugs.kde.org/show_bug.cgi?id=376120

**Comment by fu-sen** [comment]
After that I asked KDE neon team.
This has been improved recently:
https://forum.kde.org/viewtopic.php?t=134856

**Comment by cmpute** [comment]
Any ideas on how to install the package on latest KDE Neon? I'm trying to install on KDE Neon 5.22 and I got similar problems:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Starting pkgProblemResolver with broken count: 1
Starting 2 pkgProblemResolver with broken count: 1
Investigating (0) fcitx5-frontend-qt5:amd64 < none -> 0.0~git20200118.2e38c95-1build3 @un puN Ib >
Broken fcitx5-frontend-qt5:amd64 Depends on qtbase-abi-5-12-8:amd64 < none @un H >
  Considering libqt5core5a:amd64 3703 as a solution to fcitx5-frontend-qt5:amd64 9999
  Re-Instated libqt5core5a:amd64
Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 fcitx5-frontend-qt5 : Depends: qtbase-abi-5-12-8
E: Unable to correct problems, you have held broken package
```
Thanks!

**Comment by wengxt** [comment]
@cmpute you'd better report it to distro since it's just a packaging issue.

**Comment by phanect** [comment]
This issue happens again on Ubuntu 22.04-based version.
Someone opened a ticket last November, but jriddell seems to miss it, so I pinged.

https://bugs.kde.org/show_bug.cgi?id=461620

Since this Issue appears at first on Google search, please allow me to put a pointer to the KDE Bugzilla here.
