### ISSUE TITLE
Qt5.3.2、fcitx4.0.1用了很多不同的fcitx-qt5版本为什么都切换不出来输入法

### ISSUE THREAD

**Issue by hopeful7266** [fcitx/fcitx-qt5#18]
编译安装Qt5.3.2 /usr/local/Qt-5.3.2，在/usr/local/Qt-5.3.2/plugins/platforminputcontexts/目录中有libcomposeplatforminputcontextplugin.so、libibusplatforminputcontextplugin.so这两个文件。

尝试多个版本fcitx-qt5，从1.0.0到1.0.6，较早的版本尝试从google.com下载pinyin.tar.gz，但是这个文件已经下载不到了，所以编译不成功。较晚的版本能够部分编译成功，例如发生这种错误：
fcitx-qt5-1.0.3/widgetsaddons/fcitxqtconfiguifactory.cpp: In member function 'FcitxQtConfigUIWidget* FcitxQtConfigUIFactory::create(const QString&)':
fcitx-qt5-1.0.3/widgetsaddons/fcitxqtconfiguifactory.cpp:59: error: 'fcitx_utils_get_fcitx_path' was not declared in this scope
fcitx-qt5-1.0.3/widgetsaddons/fcitxqtconfiguifactory.cpp: In member function 'void FcitxQtConfigUIFactoryPrivate::scan()':
fcitx-qt5-1.0.3/widgetsaddons/fcitxqtconfiguifactory.cpp:77: error: 'FcitxXDGGetLibPath' was not declared in this scope

将libfcitxplatforminputcontextplugin.so放到/usr/local/Qt-5.3.2/plugins/platforminputcontexts/目录中，发现用Qt5.3.2编译的应用程序还是不能切换出输入法。

在用Qt5.3.2和fcitx4.0.1的情况下应选择fcitx-qt5的某个特定版本吗？用最新fcitx-qt5版本是否可行？fcitx-qt5编译完后应该怎么配置？

**Comment by wengxt** [comment]
你得用 fcitx 4.2 以上才行。
