### ISSUE TITLE
fcitx not working with webengine with qt 5.8

### ISSUE THREAD

**Issue by shioyama** [fcitx/fcitx-qt5#20]
Thanks for all your great work on fcitx!

I've just upgraded to qt5 version 5.8 and fcitx no longer seems to work with qtwebengine (I'm using qutebrowser). I notice there were some commits last week related to this.

Any idea what might be going wrong? I'm on arch, can supply other details.

**Comment by wengxt** [comment]
is it the only qt5 app that has problem?

**Comment by shioyama** [comment]
It seems to be only webengine specifically. e.g. I can use fcitx fine with the command bar on qutebrowser which is not webengine. Other applications seem to be working fine

**Comment by wengxt** [comment]
I don't have qt 5.8 on my system right now so I can't test. I would need to check it in a vm. Would you mind point me to "some commits" you mentioned?

**Comment by wengxt** [comment]
well I just installed a vm and indeed neither ibus or fcitx is working. I tried konqueror. The bug should belong to qtwebengine.

**Comment by wengxt** [comment]
created a bug report on Qt. FYI https://bugreports.qt.io/browse/QTBUG-58763

**Comment by shioyama** [comment]
Thanks!!!
