### ISSUE TITLE
Please install translation files optionally

### ISSUE THREAD

**Issue by yurivict** [fcitx/fcitx-qt5#29]
Please add a cmake option (ex. NLS), and only install .mo files and link to libintl when this option is set.

On the FreeBSD there is a system-wide option NLS that allows to disable/enable translation files, and fcitx-qt5 doesn't allow to do this.

Thanks!

**Comment by wengxt** [comment]
All of fcitx project uses i18n, why would fcitx-qt5 need to be so special?
I don't think it's a common practice in open source world to have such an option, so it doesn't make much sense to me.

How do FreeBSD handle packages like KDE? I don't think KDE has one of such option.

Also does it even make sense to use "input method" when NLS is disabled? AFAIK libx11'sinput method protocol support is also in its "i18n" part.

If you really find it is necessary to do it, please do a PR yourself. I don't want to spend time on this.

**Comment by yurivict** [comment]
Ok, thanks!
