### ISSUE TITLE
编译报错，HASH_SORT未定义

### ISSUE THREAD

**Issue by chaoliu1995** [fcitx/fcitx-qt5#30]
错误信息如下：
/home/chao/git_repository/fcitx-qt5/quickphrase-editor/filelistmodel.cpp:65: error: ‘typeof’ was not declared in this scope
     HASH_SORT(files, fcitx_utils_string_hash_set_compare);

我在项目全局搜了一下，没有HASH_SORT的定义
PS：我不会C/C++，想要解决为知笔记中文输入的问题

**Comment by Honghe** [comment]
同样遇到这个问题，环境 Ubuntu 16.04.3

**Comment by huazq** [comment]
anybody solved it?

**Comment by oPiZiL** [comment]
是不是GCC版本太高了？
