### ISSUE TITLE
Double characters in Qt5 applications

### ISSUE THREAD

**Issue by clavinet** [fcitx/fcitx-qt5#32]
hey, I'm having slight troubles with fcitx and Qt5.

I'm using the German keyboard layout and entering characters with diacritics such as "è" results in double characters.

Example:
I press

```
`
e
```

I get 
`èé`

but, If I wait a little after pressing the diacritic key, and only press "e" after ~1 second, I get this:
`èè`

So the first character is always correct, but the second one is both _superfluous_ and _varies based on typing speed_.

**Comment by wengxt** [comment]
i think it is

https://github.com/fcitx/fcitx/issues/395

This should be fixed in latest fcitx-qt5, can you check?

**Comment by nekoswag** [comment]
I will test it again once the updated fcitx-qt5 1.2.2 package arrives in my distribution, which should be within the next few days.

**Comment by nekoswag** [comment]
Update to 1.2.2 indeed fixed it.
