### ISSUE TITLE
Fedora 27最近更新出现包冲突

### ISSUE THREAD

**Issue by fancige** [fcitx/fcitx-qt5#33]
kcm-fcitx和fcitx-qt5依赖旧版qt5-qtbase，目前只能先删掉这两个模块才能更新冲突的那几个系统包。以下为报错信息：

 Problem 1: cannot install both qt5-qtbase-5.9.4-1.fc27.x86_64 and qt5-qtbase-5.9.2-6.fc27.x86_64
  - package fcitx-qt5-1.2.1-1.fc27.x86_64 requires qt5-qtbase(x86-64) = 5.9.2, but none of the providers can be installed
  - cannot install the best update candidate for package qt5-qtbase-5.9.2-6.fc27.x86_64
  - cannot install the best update candidate for package fcitx-qt5-1.2.1-1.fc27.x86_64
 Problem 2: package kcm-fcitx-0.5.5-1.fc27.x86_64 requires libFcitxQt5DBusAddons.so.1()(64bit), but none of the providers can be installed
  - package fcitx-qt5-1.2.1-1.fc27.x86_64 requires qt5-qtbase(x86-64) = 5.9.2, but none of the providers can be installed
  - package fcitx-qt5-1.1.1-1.fc27.x86_64 requires qt5-qtbase(x86-64) = 5.9.1, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.9.4-1.fc27.x86_64 and qt5-qtbase-5.9.2-6.fc27.x86_64
  - cannot install both qt5-qtbase-5.9.1-9.fc27.x86_64 and qt5-qtbase-5.9.4-1.fc27.x86_64
  - package kf5-akonadi-server-17.12.1-2.fc27.x86_64 requires qt5-qtbase(x86-64) = 5.9.4, but none of the providers can be installed
  - cannot install the best update candidate for package kf5-akonadi-server-17.12.1-1.fc27.x86_64
  - cannot install the best update candidate for package kcm-fcitx-0.5.5-1.fc27.x86_64
 Problem 3: problem with installed package fcitx-qt5-1.2.1-1.fc27.x86_64
  - package fcitx-qt5-1.2.1-1.fc27.x86_64 requires qt5-qtbase(x86-64) = 5.9.2, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.9.4-1.fc27.x86_64 and qt5-qtbase-5.9.2-6.fc27.x86_64
  - package kf5-frameworkintegration-5.42.0-2.fc27.x86_64 requires qt5-qtbase(x86-64) = 5.9.4, but none of the providers can be installed
  - cannot install the best update candidate for package kf5-frameworkintegration-5.42.0-1.fc27.x86_64
 Problem 4: problem with installed package kcm-fcitx-0.5.5-1.fc27.x86_64
  - package kcm-fcitx-0.5.5-1.fc27.x86_64 requires libFcitxQt5DBusAddons.so.1()(64bit), but none of the providers can be installed
  - package fcitx-qt5-1.2.1-1.fc27.x86_64 requires qt5-qtbase(x86-64) = 5.9.2, but none of the providers can be installed
  - package fcitx-qt5-1.1.1-1.fc27.x86_64 requires qt5-qtbase(x86-64) = 5.9.1, but none of the providers can be installed
  - cannot install both qt5-qtbase-5.9.4-1.fc27.x86_64 and qt5-qtbase-5.9.2-6.fc27.x86_64
  - cannot install both qt5-qtbase-5.9.1-9.fc27.x86_64 and qt5-qtbase-5.9.4-1.fc27.x86_64
  - package kf5-kdeclarative-5.42.0-2.fc27.x86_64 requires qt5-qtbase(x86-64) = 5.9.4, but none of the providers can be installed
  - cannot install the best update candidate for package kf5-kdeclarative-5.42.0-1.fc27.x86_64
============================================================================================
 Package                         Arch          Version                 Repository      Size
============================================================================================
Skipping packages with conflicts:
(add '--best --allowerasing' to command line to force their upgrade):
 qt5-qtbase                      x86_64        5.9.1-9.fc27            fedora         3.4 M
 qt5-qtbase                      x86_64        5.9.4-1.fc27            updates        3.4 M
Skipping packages with broken dependencies:
 fcitx-qt5                       x86_64        1.1.1-1.fc27            fedora         123 k
 kf5-akonadi-server              x86_64        17.12.1-2.fc27          updates        2.4 M
 kf5-frameworkintegration        x86_64        5.42.0-2.fc27           updates        1.6 M
 kf5-kdeclarative                x86_64        5.42.0-2.fc27           updates        277 k

Transaction Summary
============================================================================================
Skip  6 Packages

Nothing to do.
Complete!

**Comment by wengxt** [comment]
发型版的问题
