### ISSUE TITLE
Preedit string is missing underline in Qt5 applications

### ISSUE THREAD

**Issue by Marth68** [fcitx/fcitx-qt5#36]
Using fcitx with fcitx-anthy inside Firefox:
![Screenshot_20191116_163152](https://user-images.githubusercontent.com/9149359/68995912-49d2fc00-0893-11ea-9998-0e303062a34c.png)

Using fcitx with fcitx-anthy inside Kate, a Qt5 application of KDE:
![Screenshot_20191116_163335](https://user-images.githubusercontent.com/9149359/68995917-65d69d80-0893-11ea-9bde-a376a4be3f8c.png)

I'm not very experienced using IMEs yet, so not having the preedit string underlined is quite confusing and makes it hard to keep track of what's happening. I'm not sure where the problem exactly lies, but I would greatly appreciate any help with this problem! I thought it could be fcitx-qt5 because the problem only occurs inside Qt5 applications, both with fcitx-anthy and fcitx-mocz.

My system is Debian 10 (Buster) with KDE 5.
The following fcitx-related packages are currently installed:
<pre>
fcitx-anthy/stable,now 0.2.3-2 amd64
fcitx-bin/stable,now 1:4.2.9.6-5 amd64
fcitx-chewing/stable,now 0.2.3-1 amd64
fcitx-config-common/stable,now 0.4.10-2 amd64
fcitx-config-gtk/stable,now 0.4.10-2 amd64
fcitx-data/stable,now 1:4.2.9.6-5 amd64
fcitx-frontend-all/stable,now 1:4.2.9.6-5 amd64
fcitx-frontend-gtk2/stable,now 1:4.2.9.6-5 amd64
fcitx-frontend-gtk3/stable,now 1:4.2.9.6-5 amd64
fcitx-frontend-qt4/stable,now 1:4.2.9.6-5 amd64
<b>fcitx-frontend-qt5/stable,now 1.2.3-2+b1 amd64</b>
fcitx-googlepinyin/stable,now 0.1.6-4 amd64
fcitx-libs-dev/stable,now 1:4.2.9.6-5 amd64
fcitx-m17n/stable,now 0.2.4-2 amd64
fcitx-module-dbus/stable,now 1:4.2.9.6-5 amd64
fcitx-module-kimpanel/stable,now 1:4.2.9.6-5 amd64
fcitx-module-lua/stable,now 1:4.2.9.6-5 amd64
fcitx-module-x11/stable,now 1:4.2.9.6-5 amd64
fcitx-modules/stable,now 1:4.2.9.6-5 amd64
fcitx-mozc/stable,now 2.23.2815.102+dfsg-4 amd64
fcitx-pinyin/stable,now 1:4.2.9.6-5 amd64
fcitx-sunpinyin/stable,now 0.4.2-2 amd64
fcitx-table-amharic/stable,now 0.2.4-2 amd64
fcitx-table-malayalam-phonetic/stable,now 0.2.4-2 amd64
fcitx-table-wubi/stable,now 1:4.2.9.6-5 amd64
fcitx-table/stable,now 1:4.2.9.6-5 amd64
fcitx-ui-classic/stable,now 1:4.2.9.6-5 amd64
fcitx5-data/stable,now 0~20181128+ds1-1 amd64
fcitx5-module-dbus/stable,now 0~20181128+ds1-1 amd64
fcitx5-module-ibus/stable,now 0~20181128+ds1-1 amd64
fcitx5-module-kimpanel/stable,now 0~20181128+ds1-1 amd64
fcitx5-module-quickphrase-editor/stable,now 1.2.3-2+b1 amd64
fcitx5-module-quickphrase/stable,now 0~20181128+ds1-1 amd64
fcitx5-module-wayland/stable,now 0~20181128+ds1-1 amd64
fcitx5-module-xorg/stable,now 0~20181128+ds1-1 amd64
fcitx5-modules/stable,now 0~20181128+ds1-1 amd64
fcitx5/stable,now 0~20181128+ds1-1 amd64
fcitx/stable,now 1:4.2.9.6-5 amd64
gir1.2-fcitx-1.0/stable,now 1:4.2.9.6-5 amd64
kde-config-fcitx/stable,now 0.5.5-2 amd64
libfcitx-config4/stable,now 1:4.2.9.6-5 amd64
libfcitx-core0/stable,now 1:4.2.9.6-5 amd64
libfcitx-gclient1/stable,now 1:4.2.9.6-5 amd64
libfcitx-qt0/stable,now 1:4.2.9.6-5 amd64
libfcitx-qt5-1/stable,now 1.2.3-2+b1 amd64
libfcitx-qt5-data/stable,now 1.2.3-2 amd64
libfcitx-qt5-dev/stable,now 1.2.3-2+b1 amd64
libfcitx-utils0/stable,now 1:4.2.9.6-5 amd64
libfcitx5config5/stable,now 0~20181128+ds1-1 amd64
libfcitx5core5/stable,now 0~20181128+ds1-1 amd64
libfcitx5utils1/stable,now 0~20181128+ds1-1 amd64
</pre>

I have also compiled the current state of fcitx-qt5 from this repository and temporarily replaced the plugin at `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.so`, but unfortunately, this didn't make a difference.

**Comment by wengxt** [comment]
![图片](https://user-images.githubusercontent.com/259684/68996252-423c3480-084c-11ea-8eeb-76051977c5f0.png)
I'm pretty sure it's kate/kwrite problem. If you try the open file dialog, you'll be able to see underline (while it's still Qt right :) ).

![图片](https://user-images.githubusercontent.com/259684/68996304-0bb2e980-084d-11ea-93ac-19f28024078b.png)

Actually, kate/kwrite handles it as you can see in this screenshot, but the problem is when cjk character and latin are shown on the same line, the alignment slightly changed and the underline is pushed away from the visible part of the line. You may consider file a bug against katepart.

**Comment by wengxt** [comment]
certain font setting may workaround this problem FYI.

And this is irrelevant to input method. For example, under markdown highlight, certain underline is not visible.

![图片](https://user-images.githubusercontent.com/259684/68996422-b7106e00-084e-11ea-9e51-13a5403eba66.png)

**Comment by wengxt** [comment]
FYI: https://bugs.kde.org/show_bug.cgi?id=404907

**Comment by Marth68** [comment]
Thank you for responding so quickly! I experienced this bug in Kate in the past, too, but I think there might be an additional problem somewhere else. For example, one of the most important applications I want to input text using fcitx is (Qt5-based) Anki. The problem persists here:
![Screenshot_20191116_181443](https://user-images.githubusercontent.com/9149359/68996648-39278380-089d-11ea-8b13-034786b13cf9.png)

I can even underline other text in the input field (it's a feature of Anki) and the preedit string will still missing its underline. Same thing, for example, in the (Qt5-based) terminal:
![Screenshot_20191116_175451](https://user-images.githubusercontent.com/9149359/68996676-83106980-089d-11ea-9e94-200565de6841.png)

Or in the (Qt5-based) file browser Dolphin:
![Screenshot_20191116_180056](https://user-images.githubusercontent.com/9149359/68996683-991e2a00-089d-11ea-8bbe-019d8dda0ae6.png)

In LibreOffice and Thunderbird, for example, it works. I really think this is because they are based on Qt4 and GTK, respectively, and that something about Qt5 is the problem. Maybe you have an idea where this could come from? I would appreciate it very much..!

**Comment by Marth68** [comment]
Oh, and I forgot to mention that I don't see the underline you showed in your screenshot when I open the open file dialog of Kate and use fcitx in the name field! What is your system setup?

**Comment by wengxt** [comment]
certain application paint the preedit themselves, for example, konsole. It is up to them how to paint it. For general qt widget is the qwidget to paint them.

for Dolphin I have no problem and I'm pretty sure it's a regular qt widget.

I think I'm using noto sans for sans and source code pro + noto for monospace?...

Tried to propose a hack for kate. https://phabricator.kde.org/D25339

**Comment by Marth68** [comment]
So, you see the underline in Dolphin from KDE 5? Could you please tell me the version of Qt5 and general fcitx that is installed on your system? Maybe the bug is only in older versions of these...

**Comment by wengxt** [comment]
My setup is a dev version of fcitx5 so probably not so useful as a
reference.

May I ask what’s your setup? I can take a look if certain does not apply
underline in certain circumstances.

What is the IM you are using? anthy or sth else? And what did you type?

**Comment by Marth68** [comment]
Of course, any help on this is greatly appreciated..!

I'm on the latest Debian 10 (Buster) with KDE 5, using **fcitx** as IME and **fcitx-anthy** as IM in order to input **Japanese**. Debian 10 runs Qt5 version 5.11. The exact versions of fcitx-related applications are included in my initial post. (For example, fcitx: 4.2.9.6, fcitx-anthy: 0.2.3.)

So to sum up: In all applications on my system that are not based on Qt5, I can place the cursor in a text input element, switch to fcitx, type "hiragana" and see ![Screenshot_20191117_022023](https://user-images.githubusercontent.com/9149359/69001551-0e5f1e80-08e1-11ea-9373-f29947bffe0e.png). But if I, for example, do the same and type "hiragana" into the name field of the open file dialog in Kate I see ![Screenshot_20191117_022606](https://user-images.githubusercontent.com/9149359/69001600-d7d5d380-08e1-11ea-8af6-431c080580b3.png).
