### ISSUE TITLE
Is there a bug? Maybe Impress in Libreoffice conflicts with fcitx-qt5.

### ISSUE THREAD

**Issue by open-src** [fcitx/fcitx-qt5#40]
When I opened a libreoffice-impress document, and clicked some text box or input some words, and made impress to lose its focus(such as switching to another application), and clicked some text box in Impress again(that is to say, gained the focus again), impress crashes.
But when I downgraded fcitx-qt5 from 1.2.5 to 1.2.4, that issue did not occur.

---------------------------------------------
The issue also exists in fcitx5-qt.

I'm using KF5 on Manjaro 20.1.1.

**Comment by wengxt** [comment]
Yeah, sounds like the exact same problem to be fixed by 6f2033c497fe0da1fd197bc3be35695b11eafd93
