### ISSUE TITLE
能否能够遵循qt静态库的标准

### ISSUE THREAD

**Issue by xmn-001** [fcitx/fcitx-qt5#48]
方便使用静态编译的项目直接导入头文件就可以使用

**Comment by xmn-001** [comment]
1： 另外一个编译失败的问题被你关闭了。
fcitx-qt5的代码中可以对qt的版本进行判断，然后使用什么版本的qt api，
`
#if QT_VERSION >= QT_VERSION_CHECK(5, 10, 0)
   // TODO 1
#else
   // TODO 2
#endif
`
我编译的是qt 5.15.1， tag 1.2.6 就失败了，应该和ubuntu的版本没有关系。

2：静态库编译，最终想实现的效果如下，一个Q_IMPORT_PLUGIN，以及编译一个.a文件

目标： 任何需要解决Fcitx输入的问题，只需要导入该项目的头文件，以及config时确定--enable-static是静态还是动态。

头文件，
`
#include <QtCore/QtPlugin>
    Q_IMPORT_PLUGIN(QComposePlatformInputContextPlugin)
    Q_IMPORT_PLUGIN(QIbusPlatformInputContextPlugin)
    Q_IMPORT_PLUGIN(QFcitxPlatformInputContextPlugin)
`
静态库依赖或者支持动态库依赖。
`
LIBS += /opt/qt/plugins/platforminputcontexts/libfcitxplatforminputcontextplugin.a
`

因为在qt的代码中，静态编译的qt的核心库是不加载so文件的。


参考：[https://github.com/Etersoft/telegram-desktop/blob/3e4b3801e4d0c65bf06b73b48982d82fd6be318f/tdesktop/Telegram/SourceFiles/qt_static_plugins.cpp](url)

**Comment by wengxt** [comment]
https://github.com/fcitx/fcitx5-qt/ 关于你说的静态库的问题，建议直接用 fcitx5-qt，可以兼容 fcitx4，有专门的 flag 可以设置成构建静态库。另外编译错误是什么请提供，否则我也没办法提供任何帮助
