### ISSUE TITLE
Typing quickly causes characters to be inputted out of order

### ISSUE THREAD

**Issue by lliehu** [fcitx/fcitx-qt5#5]
Sometimes if one types quickly, characters will be inputted in wrong order. For example if one types "something", the result in a text field can be for example "something", "gnihtemos", "somethgni", "sometgnih" or "somegniht".

There might be a pattern that some character sequences are inputted in reverse order.

I can reproduce this every time with a simple test case that consists only of a QLineEdit. This issue only occurs when using fcitx-qt5, so I think it's quite likely that the problem is in fcitx-qt5. I also tested with ibus and without any im module. There were no problems.

I also tested this by using a program to input "something" character and character, thus eliminating the possibility of a human making typos.

This is the test case (compile with -std=c++11):

``` cpp
#include <QApplication>
#include <QLineEdit>
#include <QThread>

int main(int argc, char *argv[])
{
    QApplication a(argc, argv);
    QLineEdit textField;
    // Sleep for one second each time text is changed.
    // This is to make it easier to reproduce the issue.
    QObject::connect(&textField, &QLineEdit::textChanged, [](){
        QThread::sleep(1);
    });
    textField.show();

    return a.exec();
}
```

**Comment by lliehu** [comment]
Thanks. Launching applications with KDE Plasma 5's Krunner is now a lot easier.

**Comment by insulsa** [comment]
Excuse me for this being irrelevant, but I'm using fcitx 4.2.9.6 shipped with ubuntu, the xkb input method, and the XIM frontend. When the operating system is under high load, fcitx dumps characters out of order significantly. Sometimes I had to pause typing for more than 1 second for each character to appear on screen. It becomes worse when using the libpinyin input method. This also happens with fcitx 4.2.9.7 shipped with debian, and another install I don't recall the version, and on different physical hardware. Any hint for what I could do to diagnose this?
