### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by widon1104** [fcitx/fcitx-qt5#50]
Output
------
/tmp/fcitx-qt5/qt5/platforminputcontext/main.h:32: Parse error at "IID"

make[2]: *** [qt5/platforminputcontext/CMakeFiles/fcitxplatforminputcontextplugin_autogen.dir/build.make:58：qt5/platforminputcontext/CMakeFiles/fcitxplatforminputcontextplugin_autogen] 错误 1
make[1]: *** [CMakeFiles/Makefile2:961：qt5/platforminputcontext/CMakeFiles/fcitxplatforminputcontextplugin_autogen.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2

**Comment by wengxt** [comment]
缺少qt private header没装或者qt版本太低

**Comment by widon1104** [comment]
sudo apt install qtbase5-private-dev
以后就编译通过了
