### ISSUE TITLE
编译出的libfcitx5platforminputcontextplugin.so在ubuntu18.04上无效

### ISSUE THREAD

**Issue by arashrun** [fcitx/fcitx-qt5#51]
替换本地的该库，没问题。使用的编译命令cmake .. -DBUILD_ONLY_PLUGIN=on -DENABLE_QT4=off

**Comment by wengxt** [comment]
你在哪编译的？编译的qt版本和对应平台版本qt不一致不会加载的。建议了解一下qt插件机制和相关的检查
