### ISSUE TITLE
fcitx-qt5 与wiznote1.5以后的版本有冲突。只有卸载了fcitx-qt5，wiznote才能启动。

### ISSUE THREAD

**Issue by 724899020** [fcitx/fcitx-qt5#9]
如题。

**Comment by yuyichao** [comment]
winznote和fcitx-qt5分别用什么版本的qt5编译的, 出错的信息是啥

**Comment by 724899020** [comment]
系统版本是centos7,使用yum安装的nux-desktop源里面的fcitx-qt5-0.1.2git20141201-1.el7.centos.x86_64就会崩溃。现在安装了一个fedora22的fcitx-qt5包，可以使用了。我的软件列表如下。
fcitx-table-4.2.8.5git20150203-1.el7.centos.x86_64
fcitx-qt5-1.0.2-2.fc22.x86_64
fcitx-4.2.8.5git20150203-1.el7.centos.x86_64
kcm-fcitx-0.4.3git20141209-1.el7.centos.x86_64
fcitx-data-4.2.8.5git20150203-1.el7.centos.noarch
fcitx-gtk3-4.2.8.5git20150203-1.el7.centos.x86_64
fcitx-pinyin-4.2.8.5git20150203-1.el7.centos.x86_64
fcitx-libs-4.2.8.5git20150203-1.el7.centos.x86_64
fcitx-fbterm-0.2.0-1.el7.centos.x86_64
fcitx-ui-light-0.1.3-8.el7.centos.x86_64
fcitx-gtk2-4.2.8.5git20150203-1.el7.centos.x86_64
fcitx-qt4-4.2.8.5git20150203-1.el7.centos.x86_64
fcitx-table-chinese-4.2.8.5git20150203-1.el7.centos.noarch
wiznote-beta-2.2.2-1.git88992f4.el7.centos.x86_64

系统版本：
CentOS Linux release 7.1.1503 (Core)
内核版本:
Linux outman.ip66.com 3.10.0-229.7.2.el7.x86_64 #1 SMP Tue Jun 23 22:06:11 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

qt环境:
qt5-qtgraphicaleffects-5.4.2-1.el7.x86_64
qtwebkit-devel-2.3.4-6.el7.x86_64
qt5-qtwebkit-5.4.2-1.el7.x86_64
qtlockedfile-2.4-11.el7.x86_64
fcitx-qt5-1.0.2-2.fc22.x86_64
qt-4.8.5-8.el7.x86_64
qt-devel-4.8.5-8.el7.x86_64
qt-recordmydesktop-0.3.8-9.el7.nux.noarch
qt5-qtsensors-5.4.2-1.el7.x86_64
qt5-qtbase-devel-5.4.2-1.el7.x86_64
dbusmenu-qt-0.9.2-7.el7.x86_64
imsettings-qt-1.6.3-9.el7.x86_64
qt-mysql-4.8.5-8.el7.x86_64
qt5-qtxmlpatterns-5.4.2-1.el7.x86_64
qtwebkit-2.3.4-6.el7.x86_64
qt5-qtbase-common-5.4.2-1.el7.noarch
qt-x11-4.8.5-8.el7.x86_64
qt5-qtlocation-5.4.2-1.el7.x86_64
qt5-qtquickcontrols-5.4.2-1.el7.x86_64
qt5-qtdeclarative-5.4.2-2.el7.x86_64
polkit-qt-0.103.0-10.el7_0.x86_64
qt5-qtscript-5.4.2-1.el7.x86_64
fcitx-qt4-4.2.8.5git20150203-1.el7.centos.x86_64
pinentry-qt-0.8.1-14.el7.x86_64
qt-settings-19-23.5.el7.noarch
qtsingleapplication-2.6.1-11.el7.x86_64
qt3-3.3.8b-51.el7.x86_64
qt5-qtbase-gui-5.4.2-1.el7.x86_64
qt5-qtdoc-5.4.2-1.el7.noarch
qt5-qtbase-5.4.2-1.el7.x86_64
qt5-qtmultimedia-5.4.2-1.el7.x86_64
poppler-qt-0.22.5-6.el7.x86_64

出错是报错吐核。
wiznote闪退。

**Comment by 724899020** [comment]
您如果要重现故障的话。直接在centos7下用yum安装最新版的wiznote和fcitx-qt5就会发现错误。记得添加nux-dextop源。

**Comment by 724899020** [comment]
以下是我在wiz-qt项目报时贴的内容。
CentOS 7 KDE下wiznote-beta闪退。最高只能运行wiznote-2.1.5-6.1.x86_64.rpm这个版本，之后的都报此错：
[outman@outman ~]$ rpm -qa | grep wiznote
wiznote-beta-2.2.1-1.git8c58446.el7.centos.x86_64
[outman@outman ~]$ uname -a
Linux outman.ip66.com 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
[outman@outman ~]$ wiznote-beta
"QLocalSocket::connectToServer: Connection refused"
[outman@outman ~]$ wiznote-beta
[WARNING]: QWidget::setLayout: Attempting to set QLayout "" on QMainWindow "", which already has a layout
[WARNING]: QFont::setPixelSize: Pixel size <= 0 (-5)
/bin/wiznote-beta: 行 2: 7176 段错误 (吐核)LD_LIBRARY_PATH=/usr/lib64/wiznote-beta/plugins wiznote-beta-run
[outman@outman ~]$

**Comment by yuyichao** [comment]
目測就是qt5的版本不一样造成的. 如果你从fedora装得没问题那就是打包的问题.
